SLT:
  type: object
  required:
    - comments
    - annotation
    - created_by
    - last_modified_by
  properties:
    comments:
      description: Comment to be Updated by the operator.
      example: There was error in EB execution in the project
      type: string
    annotation:
      description: Comment by other operators.
      example: There was error in EB execution in the project.
      type: string
    created_by:
      description: Operator User Name which has created the SLT.
      example: Chandler Bing
      type: string
    last_modified_by:
      description: Operator User Name which has updated the SLT.
      example: Ross Geller
      type: string
   