SLTDB:
  type: object
  required:
    - comments
    - annotation
  properties:
    comments:
      description: Comment to be Updated by the operator.
      example: There was error in EB execution in the project
      type: string
    annotation:
      description: Comment by other operators.
      example: There was error in EB execution in the project.
      type: string
   